export const COUPON_ADD_EVENT = 'COUPON_ADD_EVENT';
export const COUPON_REMOVE_EVENT = 'COUPON_REMOVE_EVENT';
export const COUPON_FROM_STORAGE = 'COUPON_FROM_STORAGE';
export const COUPON_UPDATE_AMOUNT = 'COUPON_UPDATE_AMOUNT';
export const COUPON_REMOVE_ALL = 'COUPON_REMOVE_ALL';
